"""empty message

Revision ID: 831af061a4db
Revises: fab19369c374
Create Date: 2023-03-14 17:27:07.870814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831af061a4db'
down_revision = 'fab19369c374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authors')
    # ### end Alembic commands ###
